services:
  alloy:
    image: grafana/alloy:1
    container_name: alloy
    restart: unless-stopped
    ports:
      - "12345:12345" # Alloy UI
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=generally-available
    networks:
      - monitoring

networks:
  monitoring:
    external: true
